const fs = require('fs');
const path = require('path');


const shaderDir = path.join(__dirname, 'src/assets/shaders');
const outputDir = path.join(__dirname, 'src/engine/shaders');
const outputFile = path.join(outputDir, 'shader-sources.ts');

function findFiles(dir, extensions) {
  let files = [];
  const items = fs.readdirSync(dir);
  for (const item of items) {
    const fullPath = path.join(dir, item);
    const stat = fs.statSync(fullPath);
    if (stat.isDirectory()) {
      files = files.concat(findFiles(fullPath, extensions));
    } else if (extensions.some(ext => item.endsWith(ext))) {
      files.push(fullPath);
    }
  }
  return files;
}

function cleanShader(code) {
  return code
    .replace(/\/\/[^\n]*/g, '') // Remove single-line comments
    .replace(/\/\*[\s\S]*?\*\//g, '') // Remove multi-line comments
    .replace(/\r\n/g, '\n')       // Convert CRLF to LF
    .replace(/\n\s*\n/g, '\n')      // Collapse multiple newlines
    .trim();
}

function generateShaderClass() {
  const fragFiles = findFiles(shaderDir, ['.frag']);
  const vertFiles = findFiles(shaderDir, ['.vert']);

  let fragContent = '';
  for (const file of fragFiles) {
    const content = fs.readFileSync(file, 'utf-8');
    const varName = path.basename(file, '.frag').replace(/[^a-zA-Z0-9_]/g, '_');
    fragContent += `  ${varName}: \`\n${cleanShader(content)}\n\`,\n`;
  }

  let vertContent = '';
  for (const file of vertFiles) {
    const content = fs.readFileSync(file, 'utf-8');
    const varName = path.basename(file, '.vert').replace(/[^a-zA-Z0-9_]/g, '_');
    vertContent += `  ${varName}: \`\n${cleanShader(content)}\n\`,
`;
  }

  const classContent = `/* eslint-disable */
// @ts-nocheck
// This file is auto-generated by generate-shaders.js. Do not edit manually.
export class ShaderSources {
  public static readonly frag = {
${fragContent}
  };
  public static readonly vertex = {
${vertContent}
  };
}
`;

  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
  }
  fs.writeFileSync(outputFile, classContent);
  console.log(`ShaderSources class generated at ${outputFile}`);
}

generateShaderClass();
