/* eslint-disable */
// @ts-nocheck
// This file is auto-generated by generate-shaders.js. Do not edit manually.
export class ShaderSources {
  public static readonly frag = {
  handle: `
#version 300 es
precision mediump float;
in vec3 v_position;
out vec4 fragColor;
void main() {
  fragColor = vec4(v_position,1.0);
}
`,
  entity: `
#version 300 es
precision highp float;
uniform float u_id;
out vec4 outColor;
void main() { outColor = vec4(u_id / 255.0, 0.0, 0.0, 1.0); }
`,
  color: `
#version 300 es
precision mediump float;
uniform vec4 u_matColor;
uniform float u_id;
in vec2 v_uv;
out vec4 fragColor;
void main() {
  fragColor = u_matColor;
  if (u_id > 0.0) {
    fragColor = vec4(u_id / 255.0, 0.0, 0.0, 1.0);
  }
}
`,
  debug: `
#version 300 es
precision mediump float;
#define MAX_DIRECTIONAL_LIGHTS 5 
#define MAX_POINT_LIGHTS 20       
#define MAX_SPOT_LIGHTS 20        
uniform vec4 u_matColor;
uniform vec2 u_uvScale;
uniform vec2 u_uvOffset;
uniform sampler2D u_mainTex;
uniform sampler2D u_normalMap; 
in vec2 v_uv;
in vec3 v_normal; 
in vec3 v_position; 
in vec3 v_tangent;
in vec3 v_bitangent;
out vec4 fragColor;
void main() {
  vec2 uv = fract(v_uv * u_uvScale) + u_uvOffset;
  vec4 sampledTexColor = texture(u_mainTex, uv);
  vec4 baseColor = sampledTexColor * u_matColor;
  fragColor = vec4(uv,0,1);
}
`,
  depth_only: `
#version 300 es
precision highp float;
void main() {
}
`,
  entity_picker: `
#version 300 es
precision highp float;
uniform float u_entity_id;
out vec4 fragColor;
void main() { fragColor = vec4(u_entity_id / 255.0, 0.0, 0.0, 1.0); }
`,
  phong: `
#version 300 es
precision highp float;
uniform int u_fogEnabled;
uniform vec3 u_FogColor;
uniform float u_FogDensity;
uniform vec4 u_matColor;
uniform vec2 u_uvScale;
uniform vec2 u_uvOffset;
uniform sampler2D u_mainTex;
uniform sampler2D u_normalMap;
uniform float u_emmission;
uniform float u_id;
uniform float u_sid;
in vec2 v_uv;
in vec3 v_normal;
in vec3 v_position;
in vec3 v_tangent;
in vec3 v_bitangent;
in vec4 v_lightSpacePosition;
in float v_fogDistance;
out vec4 fragColor;
@INCLUDE_LIGHT_FUNC
@INCLUD_FUNC
void main() {
  vec2 uv = fract(v_uv * u_uvScale) + u_uvOffset;
  vec4 sampledTexColor = texture(u_mainTex, uv);
  vec4 baseColor = vec4(sampledTexColor.rgb * u_matColor.rgb, (u_matColor.a * sampledTexColor.a));
  vec3 totalLitColorRGB = calculateTotalLitColor(baseColor.rgb, uv);
  vec4 finalColor = vec4(clamp(totalLitColorRGB, 0.0, 1.0), baseColor.a);
  vec3 foggedRGB = finalColor.rgb;
  if (u_fogEnabled == 1) {
    foggedRGB = applyExponentialFog(finalColor.rgb, u_FogColor, v_fogDistance, u_FogDensity);
  }
  fragColor = vec4(foggedRGB, finalColor.a);
}
`,
  skybox: `
#version 300 es
precision mediump float;
uniform samplerCube u_mainTex;
uniform vec4 u_matColor;
uniform vec4 u_horizonColor;
uniform float u_horizonStart;
uniform float u_horizonHeight;
uniform float u_gradient;
uniform float u_exposure;

// Sun uniforms
uniform int u_useSun;
uniform vec3 u_sunDirection;
uniform vec4 u_sunColor;
uniform float u_sunSize;
uniform float u_sunFalloff;

// Moon uniforms
uniform int u_useMoon;
uniform vec3 u_moonDirection;
uniform vec4 u_moonColor;
uniform float u_moonSize;
uniform float u_moonFalloff;
uniform float u_moonPhase;

in vec3 v_viewDirection;
out vec4 fragColor;
void main() {
  vec3 viewDir = normalize(v_viewDirection);

  float y = viewDir.y;
  vec3 gradientColor = vec3(0.0);

  if (y > 0.0) {
    float p = pow(y, u_exponent);
    gradientColor = mix(u_horizonColor.rgb, u_skyColor.rgb, p);
  } else {
    float p = pow(-y, u_exponent);
    gradientColor = mix(u_horizonColor.rgb, u_groundColor.rgb, p);
  }

  vec4 finalColor = vec4(gradientColor, 1.0);

  if (u_useSun == 1) {
    // Tint the sky with the light color to simulate atmosphere
    finalColor.rgb *= u_sunColor.rgb;

    // Calculate sun
    vec3 sunDir = normalize(u_sunDirection);
    float sunDot = max(0.0, dot(viewDir, sunDir));
    float sunCore = smoothstep(u_sunSize - u_sunFalloff, u_sunSize, sunDot);
    float sunGlow = pow(sunDot, 120.0) * 0.5; // Wide atmospheric glow

    // Additive blending for the sun
    finalColor.rgb += u_sunColor.rgb * (sunCore + sunGlow);

    // Calculate moon
    if (u_useMoon == 1) {
      vec3 moonDir = normalize(u_moonDirection);
      float moonDot = max(0.0, dot(viewDir, moonDir));
      float moonCore = smoothstep(u_moonSize - u_moonFalloff, u_moonSize, moonDot);
      float d2 = 1.0 - moonDot * moonDot;
      float R2 = 1.0 - u_moonSize * u_moonSize;
      float z = sqrt(max(0.0, R2 - d2));
      vec3 N = normalize(viewDir + moonDir * (z - moonDot));
      float phaseAngle = u_moonPhase * 6.2831853;
      vec3 moonRight = normalize(cross(vec3(0.0, 1.0, 0.0001), moonDir));
      vec3 L = normalize(moonDir * cos(phaseAngle) + moonRight * sin(phaseAngle));
      float moonLighting = smoothstep(-0.5, 0.5, dot(N, L));
      float earthshine = 0.02;
      vec3 moonBodyColor = u_moonColor.rgb * mix(earthshine, 1.0, moonLighting);
      float moonGlow = pow(moonDot, 200.0) * 0.05 * (0.5 + 0.5 * cos(phaseAngle));
      finalColor.rgb = mix(finalColor.rgb, moonBodyColor, moonCore) + u_moonColor.rgb * moonGlow;
    }
  }

  fragColor = clamp(finalColor, 0.0, 1.0);
}
`,
  unlit: `
#version 300 es
precision mediump float;
uniform vec4 u_matColor;
uniform vec2 u_uvScale;
uniform vec2 u_uvOffset;
uniform sampler2D u_mainTex;
uniform float u_id;
in vec2 v_uv;
in vec3 v_position;
out vec4 fragColor;
void main() {
  vec2 uv = fract(v_uv * u_uvScale) + u_uvOffset;
  fragColor = texture(u_mainTex, uv) * u_matColor;
  if (u_id > 0.0) {
    fragColor = vec4(u_id / 255.0, 0.0, 0.0, 1.0);
  }
}
`,
  functions: `
float calculateLinearFogFactor(float distance, float fogStart, float fogEnd) {
    float fogFactor = (distance - fogStart) / (fogEnd - fogStart);
    return clamp(fogFactor, 0.0, 1.0);
}
float calculateExponentialFogFactor(float distance, float fogDensity) {
    float fogFactor = 1.0 - exp(-distance * fogDensity);
    return clamp(fogFactor, 0.0, 1.0);
}
vec3 applyLinearFog(vec3 originalColor, vec3 fogColor, float distance, float fogStart, float fogEnd) {
    float fogFactor = calculateLinearFogFactor(distance, fogStart, fogEnd);
    return mix(originalColor, fogColor, fogFactor);
}
vec3 applyExponentialFog(vec3 originalColor, vec3 fogColor, float distance, float fogDensity) {
    float fogFactor = calculateExponentialFogFactor(distance, fogDensity);
    return mix(originalColor, fogColor, fogFactor);
}
float rand(vec2 c){
	return fract(sin(dot(c.xy ,vec2(12.9898,78.233))) * 43758.5453);
}
`,
  light_header: `
#define MAX_DIRECTIONAL_LIGHTS 5 
#define MAX_POINT_LIGHTS 20       
#define MAX_SPOT_LIGHTS 20        
uniform float u_specularStrength; 
uniform float u_roughness;        
uniform vec3 u_cameraPosition;    
uniform float u_normalMapStrength; 
uniform vec4 u_ambientLight; 
uniform int u_numDirectionalLights;
uniform vec3 u_directionalLightDirections[MAX_DIRECTIONAL_LIGHTS];
uniform vec3 u_directionalLightColors[MAX_DIRECTIONAL_LIGHTS];
uniform int u_numPointLights;
uniform vec3 u_pointLightPositions[MAX_POINT_LIGHTS];
uniform vec3 u_pointLightColors[MAX_POINT_LIGHTS];
uniform float u_pointLightConstantAtts[MAX_POINT_LIGHTS];
uniform float u_pointLightLinearAtts[MAX_POINT_LIGHTS];
uniform float u_pointLightQuadraticAtts[MAX_POINT_LIGHTS];
uniform int u_numSpotLights;
uniform vec3 u_spotLightPositions[MAX_SPOT_LIGHTS];
uniform vec3 u_spotLightDirections[MAX_SPOT_LIGHTS];
uniform vec3 u_spotLightColors[MAX_SPOT_LIGHTS];
uniform float u_spotLightInnerConeCos[MAX_SPOT_LIGHTS];
uniform float u_spotLightOuterConeCos[MAX_SPOT_LIGHTS];
uniform float u_spotLightConstantAtts[MAX_SPOT_LIGHTS];
uniform float u_spotLightLinearAtts[MAX_SPOT_LIGHTS];
uniform float u_spotLightQuadraticAtts[MAX_SPOT_LIGHTS];
`,
  light: `
#define MAX_DIRECTIONAL_LIGHTS 1
#define MAX_POINT_LIGHTS 20
#define MAX_SPOT_LIGHTS 20
uniform float u_specularStrength;
uniform float u_roughness;
uniform vec3 u_cameraPosition;
uniform float u_normalMapStrength;
uniform vec4 u_ambientLight;
uniform int u_useShadows;
uniform highp sampler2DShadow u_shadowMap; 
uniform vec2 u_shadowMapSize;
uniform int u_numDirectionalLights;
uniform vec3 u_directionalLightDirections[MAX_DIRECTIONAL_LIGHTS];
uniform vec3 u_directionalLightColors[MAX_DIRECTIONAL_LIGHTS];
uniform int u_numPointLights;
uniform vec3 u_pointLightPositions[MAX_POINT_LIGHTS];
uniform vec3 u_pointLightColors[MAX_POINT_LIGHTS];
uniform float u_pointLightConstantAtts[MAX_POINT_LIGHTS];
uniform float u_pointLightLinearAtts[MAX_POINT_LIGHTS];
uniform float u_pointLightQuadraticAtts[MAX_POINT_LIGHTS];
uniform int u_numSpotLights;
uniform vec3 u_spotLightPositions[MAX_SPOT_LIGHTS];
uniform vec3 u_spotLightDirections[MAX_SPOT_LIGHTS];
uniform vec3 u_spotLightColors[MAX_SPOT_LIGHTS];
uniform float u_spotLightInnerConeCos[MAX_SPOT_LIGHTS];
uniform float u_spotLightOuterConeCos[MAX_SPOT_LIGHTS];
uniform float u_spotLightConstantAtts[MAX_SPOT_LIGHTS];
uniform float u_spotLightLinearAtts[MAX_SPOT_LIGHTS];
uniform float u_spotLightQuadraticAtts[MAX_SPOT_LIGHTS];
float is_in_shadow_pcf(vec4 lightSpacePosition, vec3 finalNormal, vec3 lightDir) {
  vec3 projCoords = lightSpacePosition.xyz / lightSpacePosition.w;
  projCoords = projCoords * 0.5 + 0.5;
  if (projCoords.z > 1.0 || u_useShadows == 0) {
    return 1.0;
  }
  float cells = 2.0;
  float total = cells * 2.0 + 1.0;
  float shadow = 0.0;
  vec2 texelSize = 1.0 / u_shadowMapSize;
  float bias = max(0.001 * (1.0 - dot(finalNormal, lightDir)), 0.0005);
  for (float x = -cells; x <= cells; ++x) {
    for (float y = -cells; y <= cells; ++y) {
      shadow += texture(u_shadowMap, vec3(projCoords.xy + vec2(x, y) * texelSize, projCoords.z - bias));
    }
  }
  return max(0.05, shadow / (total*total));
}
vec3 calculateTotalLitColor(vec3 baseColor, vec2 uv) {
  vec3 finalNormal;
  if (u_normalMapStrength > 0.0) {
    vec3 normalFromMap = texture(u_normalMap, uv).rgb;
    normalFromMap = normalFromMap * 2.0 - 1.0;
    mat3 tbnMatrix =
        mat3(normalize(v_tangent), normalize(v_bitangent), normalize(v_normal));
    vec3 perturbedNormal = tbnMatrix * normalFromMap;
    finalNormal = normalize(mix(normalize(v_normal), normalize(perturbedNormal),
                                u_normalMapStrength));
  } else {
    finalNormal = normalize(v_normal);
  }
  vec3 viewDir = normalize(u_cameraPosition - v_position);
  float clampedRoughness = clamp(u_roughness, 0.001, 0.999);
  float shininess = (2.0 / (1.0 - clampedRoughness)) - 2.0;
  vec3 totalLitColorRGB = u_ambientLight.rgb * baseColor;
  vec3 lightDir = normalize(u_directionalLightDirections[0]);
  float nDotL = dot(finalNormal, lightDir);
  if (nDotL > 0.0) {
    float diffuseIntensity = nDotL;
    vec3 halfVec = normalize(lightDir + viewDir);
    float shadowFactor =
        is_in_shadow_pcf(v_lightSpacePosition, finalNormal, -lightDir);
    float specularIntensity =
        pow(max(0.0, dot(finalNormal, halfVec)), shininess) * u_specularStrength;
    totalLitColorRGB += (baseColor * u_directionalLightColors[0] *
                         (diffuseIntensity + specularIntensity)) *
                        shadowFactor;
  }
  for (int i = 0; i < u_numPointLights; ++i) {
    vec3 lightVecPoint = u_pointLightPositions[i] - v_position;
    vec3 pointLightDir = normalize(lightVecPoint);
    float pointNDotL = dot(finalNormal, pointLightDir);
    if (pointNDotL > 0.0) {
      float distancePoint = length(lightVecPoint);
      float attenuationPoint =
          1.0 / (u_pointLightConstantAtts[i] +
                 u_pointLightLinearAtts[i] * distancePoint +
                 u_pointLightQuadraticAtts[i] * (distancePoint * distancePoint));
      float pointDiffuseIntensity = pointNDotL;
      vec3 halfVec = normalize(pointLightDir + viewDir);
      float pointSpecularIntensity =
          pow(max(0.0, dot(finalNormal, halfVec)), shininess) *
          u_specularStrength;
      totalLitColorRGB +=
          (baseColor * u_pointLightColors[i] *
           (pointDiffuseIntensity + pointSpecularIntensity) * attenuationPoint);
    }
  }
  for (int i = 0; i < u_numSpotLights; ++i) {
    vec3 lightVecSpot = u_spotLightPositions[i] - v_position;
    vec3 spotLightDirFromFrag = normalize(lightVecSpot);
    float spotNDotL = dot(finalNormal, spotLightDirFromFrag);
    if (spotNDotL > 0.0) {
      float distanceSpot = length(lightVecSpot);
      float attenuationSpot =
          1.0 /
          (u_spotLightConstantAtts[i] + u_spotLightLinearAtts[i] * distanceSpot +
           u_spotLightQuadraticAtts[i] * (distanceSpot * distanceSpot));
      attenuationSpot = clamp(attenuationSpot, 0.0, 1.0);
      float angleCos = dot(spotLightDirFromFrag, -u_spotLightDirections[i]);
      float coneFactor = smoothstep(u_spotLightOuterConeCos[i],
                                    u_spotLightInnerConeCos[i], angleCos);
      coneFactor = clamp(coneFactor, 0.0, 1.0);
      float spotDiffuseIntensity = spotNDotL;
      vec3 halfVec = normalize(spotLightDirFromFrag + viewDir);
      float spotSpecularIntensity =
          pow(max(0.0, dot(finalNormal, halfVec)), shininess) *
          u_specularStrength;
      totalLitColorRGB += (baseColor * u_spotLightColors[i] *
                           (spotDiffuseIntensity + spotSpecularIntensity) *
                           attenuationSpot * coneFactor);
    }
  }
  return totalLitColorRGB;
}
`,
  light_old: `
#define MAX_DIRECTIONAL_LIGHTS 1
#define MAX_POINT_LIGHTS 20
#define MAX_SPOT_LIGHTS 20
uniform float u_specularStrength;
uniform float u_roughness;
uniform vec3 u_cameraPosition;
uniform float u_normalMapStrength;
uniform vec4 u_ambientLight;
uniform sampler2D u_shadowMap;
uniform float u_shadowBias;
uniform int u_numDirectionalLights;
uniform vec3 u_directionalLightDirections[MAX_DIRECTIONAL_LIGHTS];
uniform vec3 u_directionalLightColors[MAX_DIRECTIONAL_LIGHTS];
uniform int u_numPointLights;
uniform vec3 u_pointLightPositions[MAX_POINT_LIGHTS];
uniform vec3 u_pointLightColors[MAX_POINT_LIGHTS];
uniform float u_pointLightConstantAtts[MAX_POINT_LIGHTS];
uniform float u_pointLightLinearAtts[MAX_POINT_LIGHTS];
uniform float u_pointLightQuadraticAtts[MAX_POINT_LIGHTS];
uniform int u_numSpotLights;
uniform vec3 u_spotLightPositions[MAX_SPOT_LIGHTS];
uniform vec3 u_spotLightDirections[MAX_SPOT_LIGHTS];
uniform vec3 u_spotLightColors[MAX_SPOT_LIGHTS];
uniform float u_spotLightInnerConeCos[MAX_SPOT_LIGHTS];
uniform float u_spotLightOuterConeCos[MAX_SPOT_LIGHTS];
uniform float u_spotLightConstantAtts[MAX_SPOT_LIGHTS];
uniform float u_spotLightLinearAtts[MAX_SPOT_LIGHTS];
uniform float u_spotLightQuadraticAtts[MAX_SPOT_LIGHTS];
vec3 is_in_shadow_debug(vec4 lightSpacePosition) {
    vec3 projCoords = lightSpacePosition.xyz / lightSpacePosition.w;
    vec2 texCoords = projCoords.xy * 0.5 + 0.5;
    if (texCoords.x < 0.0 || texCoords.x > 1.0 || texCoords.y < 0.0 || texCoords.y > 1.0) {
        return vec3(1.0, 0.0, 0.0);
    }
    float shadowMapDepth = texture(u_shadowMap, texCoords).r;
    return vec3(shadowMapDepth);
}
float is_in_shadow(vec4 lightSpacePosition) {
    vec3 projCoords = lightSpacePosition.xyz / lightSpacePosition.w;
    vec2 texCoords = projCoords.xy * 0.5 + 0.5;
    if (texCoords.x < 0.0 || texCoords.x > 1.0 || texCoords.y < 0.0 || texCoords.y > 1.0) {
        return 1.0;
    }
    float shadowMapDepth = texture(u_shadowMap, texCoords).r;
    float currentDepth = projCoords.z;
    if (currentDepth <= shadowMapDepth + u_shadowBias) {
        return 0.0;
    }
    return 1.0;
}
vec3 calculateTotalLitColor(vec3 baseColor, vec2 uv, float shadowFactor) {
    vec3 finalNormal;
    if (u_normalMapStrength > 0.0) {
        vec3 normalFromMap = texture(u_normalMap, uv).rgb;
        normalFromMap = normalFromMap * 2.0 - 1.0;
        mat3 tbnMatrix = mat3(normalize(v_tangent), normalize(v_bitangent), normalize(v_normal));
        vec3 perturbedNormal = tbnMatrix * normalFromMap;
        finalNormal = normalize(mix(normalize(v_normal), normalize(perturbedNormal), u_normalMapStrength));
    } else {
        finalNormal = normalize(v_normal);
    }
    vec3 viewDir = normalize(u_cameraPosition - v_position);
    float clampedRoughness = clamp(u_roughness, 0.001, 0.999);
    float shininess = (2.0 / (1.0 - clampedRoughness)) - 2.0;
    vec3 totalLitColorRGB = u_ambientLight.rgb * baseColor;
    for (int i = 0; i < u_numDirectionalLights; ++i) {
        vec3 lightDir = normalize(u_directionalLightDirections[i]);
        float diffuseIntensity = max(dot(finalNormal, lightDir), 0.0);
        vec3 halfVec = normalize(lightDir + viewDir);
        float specularIntensity = pow(max(0.0, dot(finalNormal, halfVec)), shininess) * u_specularStrength;
        totalLitColorRGB += (baseColor * u_directionalLightColors[i] * (diffuseIntensity + specularIntensity)) * shadowFactor;
    }
    for (int i = 0; i < u_numPointLights; ++i) {
        vec3 lightVecPoint = u_pointLightPositions[i] - v_position;
        float distancePoint = length(lightVecPoint);
        vec3 pointLightDir = normalize(lightVecPoint);
        float attenuationPoint = 1.0 / (u_pointLightConstantAtts[i] + u_pointLightLinearAtts[i] * distancePoint + u_pointLightQuadraticAtts[i] * (distancePoint * distancePoint));
        float pointDiffuseIntensity = max(dot(finalNormal, pointLightDir), 0.0);
        vec3 halfVec = normalize(pointLightDir + viewDir);
        float pointSpecularIntensity = pow(max(0.0, dot(finalNormal, halfVec)), shininess) * u_specularStrength;
        totalLitColorRGB += (baseColor * u_pointLightColors[i] * (pointDiffuseIntensity + pointSpecularIntensity) * attenuationPoint) * shadowFactor;
    }
    for (int i = 0; i < u_numSpotLights; ++i) {
        vec3 lightVecSpot = u_spotLightPositions[i] - v_position;
        float distanceSpot = length(lightVecSpot);
        float attenuationSpot = 1.0 / (u_spotLightConstantAtts[i] + u_spotLightLinearAtts[i] * distanceSpot + u_spotLightQuadraticAtts[i] * (distanceSpot * distanceSpot));
        attenuationSpot = clamp(attenuationSpot, 0.0, 1.0);
        vec3 spotLightDirFromFrag = normalize(lightVecSpot);
        float angleCos = dot(spotLightDirFromFrag, -u_spotLightDirections[i]);
        float coneFactor = smoothstep(u_spotLightOuterConeCos[i], u_spotLightInnerConeCos[i], angleCos);
        coneFactor = clamp(coneFactor, 0.0, 1.0);
        float spotDiffuseIntensity = max(dot(finalNormal, spotLightDirFromFrag), 0.0);
        vec3 halfVec = normalize(spotLightDirFromFrag + viewDir);
        float spotSpecularIntensity = pow(max(0.0, dot(finalNormal, halfVec)), shininess) * u_specularStrength;
        totalLitColorRGB += (baseColor * u_spotLightColors[i] * (spotDiffuseIntensity + spotSpecularIntensity) * attenuationSpot * coneFactor) * shadowFactor;
    }
    return totalLitColorRGB;
}
`,

  };
  public static readonly vertex = {
  handle: `
#version 300 es
in vec3 a_position;
in mat4 aInstanceModelMatrix; 
uniform mat4 uProjectionMatrix;
uniform mat4 uViewMatrix;
out vec3 v_position;
void main(void) {
  v_position = a_position;
  gl_Position =      uProjectionMatrix * uViewMatrix * aInstanceModelMatrix * vec4(a_position,0);
}
`,
  entity: `
#version 300 es
uniform mat4 u_mvpMatrix;
in vec4 a_position;
void main() { gl_Position = u_mvpMatrix * a_position; }
`,
  billdboard: `
#version 300 es
uniform mat4 u_projectionMatrix;
uniform mat4 u_viewMatrix;
uniform mat4 u_worldMatrix;
in vec3 a_position; 
in vec2 a_uv;
out vec2 v_uv;
void main() {
  vec3 billboardWorldPosition = (u_worldMatrix * vec4(0.0, 0.0, 0.0, 1.0)).xyz;
  mat4 inverseViewMatrix = inverse(u_viewMatrix);
  mat4 billboardRotationMatrix = mat4(
      inverseViewMatrix[0][0], inverseViewMatrix[0][1], inverseViewMatrix[0][2], 0.0,
      inverseViewMatrix[1][0], inverseViewMatrix[1][1], inverseViewMatrix[1][2], 0.0,
      inverseViewMatrix[2][0], inverseViewMatrix[2][1], inverseViewMatrix[2][2], 0.0,
      0.0, 0.0, 0.0, 1.0
  );
  vec4 finalPosition = billboardRotationMatrix * vec4(a_position, 1.0);
  finalPosition.xyz += billboardWorldPosition; 
  gl_Position = u_projectionMatrix * u_viewMatrix * finalPosition;
  v_uv = a_uv;
}
`,
  fullscreen: `
#version 300 es
uniform mat4 u_mvpMatrix;
uniform float u_time;
uniform vec2 u_screenResolution;
in vec3 a_position;
in vec3 a_normal;
in vec2 a_uv;
out vec2 v_uv;
out vec3 v_normal;
out vec3 v_position;
void main() {
  v_uv = a_uv;
  v_normal = a_normal;
  v_position = a_position;
  gl_Position =   vec4(a_position, 1.0);
}
`,
  shadow_caster: `
#version 300 es
uniform mat4 u_mvpMatrix;
layout (location = 0) in vec3 a_position;
void main() {
  gl_Position = u_mvpMatrix * vec4(a_position, 1.0);
}
`,
  skybox: `
#version 300 es
precision highp float;
uniform mat4 u_mvpMatrix;
in vec3 a_position;
out vec3 v_viewDirection;
void main() {
  gl_Position = u_mvpMatrix * vec4(a_position, 1.0);
  v_viewDirection = a_position;
}
`,
  vertex: `
#version 300 es
uniform mat4 u_mvpMatrix;
uniform mat4 u_worldMatrix;
uniform mat4 u_viewMatrix; 
uniform mat3 u_worldInverseTransposeMatrix;
uniform float u_time;
uniform vec2 u_screenResolution;
uniform mat4 u_lightMVPMatrix;
uniform float u_fogDistance;
in vec3 a_position;
in vec3 a_normal;
in vec2 a_uv;
in vec3 a_tangent;
in vec3 a_bitangent;
out vec2 v_uv;
out vec3 v_normal;
out vec3 v_position;
out vec3 v_position_view;
out vec3 v_tangent;
out vec3 v_bitangent;
out vec4 v_lightSpacePosition;
out float v_fogDistance;
void main() {
  vec4 worldPosition = u_worldMatrix * vec4(a_position, 1.0);
  vec4 viewPosition = u_viewMatrix * worldPosition;
  v_position = worldPosition.xyz;
  v_position_view = viewPosition.xyz;
  v_normal = u_worldInverseTransposeMatrix * a_normal;
  v_tangent = u_worldInverseTransposeMatrix * a_tangent;
  v_bitangent = u_worldInverseTransposeMatrix * a_bitangent;
  v_uv = a_uv;
  v_fogDistance = abs(viewPosition.z )+ u_fogDistance;
  v_lightSpacePosition = u_lightMVPMatrix * vec4(a_position, 1.0);
  gl_Position = u_mvpMatrix * vec4(a_position, 1.0);
  gl_PointSize = 10.0;
}
`,

  };
}
