import { Scene } from '@engine/entities';
import { IRenderPass } from './render-pass.interface';
import { Texture } from '@engine/textures';
import { Shader, UnlitShader } from '@engine/shaders';
import { CanvasViewport } from '@engine/core/canvas-viewport';
import { JsonSerializable } from '../../json-serializable';
import { ColorMaterial, UnlitMaterial } from '@engine/materials';

export class ScreenBlitPass extends JsonSerializable implements IRenderPass {
  private gl: WebGL2RenderingContext;
  private screenQuadShader: Shader;

  // The off-screen color texture generated by your GeometryPass
  public sourceTexture!: Texture;
  private shaderInited = false;

  constructor(gl: WebGL2RenderingContext) {
    super('ScreenBlitPass');
    this.gl = gl;

    // Initialize a dedicated screen quad shader to blit the texture
    this.screenQuadShader = new UnlitShader(gl, new UnlitMaterial());

    this.screenQuadShader.fragUri = 'assets/shaders/frag/screen-blit.frag';
    this.screenQuadShader.vertexUri = 'assets/shaders/vertex/screen-quad.vert';
  }

  setGl(gl: WebGL2RenderingContext): void {
    this.gl = gl;
  }

  async initialize(): Promise<void> {
    await this.screenQuadShader.initialize();
  }

  execute(scene: Scene): void {
    if (!this.sourceTexture) return;
    if (!this.shaderInited) {
      this.screenQuadShader
        .initialize()
        .then((init) => (this.shaderInited = init));
      return;
    }

    
    if (!this.screenQuadShader.initialized) {
      console.trace('shader not initialized!', this.screenQuadShader);
      return;
    }
    
    // this.gl.bindFramebuffer(this.gl.FRAMEBUFFER, null);
    this.gl.viewport(0, 0, this.gl.canvas.width, this.gl.canvas.height);

    // 2. Use blit shader, bind sourceTexture, and draw full-screen quad
    this.screenQuadShader.use();

    // Bind texture to unit 0 and assign uniform
    this.gl.activeTexture(this.gl.TEXTURE0);
    this.gl.bindTexture(this.gl.TEXTURE_2D, this.sourceTexture.glTexture);
    this.screenQuadShader.setInt('u_screenTexture', 0);

    // Draw full screen quad (2 triangles / 6 vertices)
    this.gl.drawArrays(this.gl.TRIANGLES, 0, 6);

    this.gl.bindTexture(this.gl.TEXTURE_2D, null);
  }

  cleanup(): void {
    this.screenQuadShader.destroy();
  }

  resize(width: number, height: number): void {}

  public setInputTexture(texture: Texture): void {
    this.sourceTexture = texture;
  }
}
