import { Scene } from '@engine/entities';
import { IRenderPass } from './render-pass.interface';
import { Texture } from '@engine/textures';
import { Shader } from '@engine/shaders';
import { CanvasViewport } from '@engine/core/canvas-viewport';
import { JsonSerializable } from '../json-serializable';

export class ScreenBlitPass extends JsonSerializable implements IRenderPass {
  private gl: WebGL2RenderingContext;
  private screenQuadShader: Shader;

  // The off-screen color texture generated by your GeometryPass
  public sourceTexture!: Texture;

  constructor(gl: WebGL2RenderingContext) {
    super('ScreenBlitPass');
    this.gl = gl;

    // Initialize a dedicated screen quad shader to blit the texture
    this.screenQuadShader = new Shader(
      gl,
      null as any,
      'assets/shaders/frag/screen-blit.frag',
      'assets/shaders/vertex/screen-quad.vert',
    );
    this.screenQuadShader.initialize();
  }

  setGl(gl: WebGL2RenderingContext): void {
    this.gl = gl;
  }

  initialize(): void {
    // Setup full-screen quad geometry buffer here if needed
  }

  execute(scene: Scene): void {
    if (!this.sourceTexture) return;

    // 1. Bind default screen framebuffer (null)
    this.gl.bindFramebuffer(this.gl.FRAMEBUFFER, null);
    this.gl.viewport(
      0,
      0,
      CanvasViewport.rendererWidth,
      CanvasViewport.rendererHeight,
    );

    this.gl.clear(this.gl.COLOR_BUFFER_BIT | this.gl.DEPTH_BUFFER_BIT);

    // 2. Use blit shader, bind sourceTexture, and draw full-screen quad
    this.screenQuadShader.use();

    // Bind texture to unit 0 and assign uniform
    this.gl.activeTexture(this.gl.TEXTURE0);
    this.gl.bindTexture(this.gl.TEXTURE_2D, this.sourceTexture.glTexture);
    this.screenQuadShader.setInt('u_screenTexture', 0);

    // Draw full screen quad (2 triangles / 6 vertices)
    this.gl.drawArrays(this.gl.TRIANGLES, 0, 6);

    this.gl.bindTexture(this.gl.TEXTURE_2D, null);
  }

  cleanup(): void {
    this.screenQuadShader.destroy();
  }

  resize(width: number, height: number): void {}
}
