// This file is auto-generated by the SENTINEL ARCHITECT.
// Please do not modify manually.

// --- Base & Utility Schemas ---

/**
 * Represents user-configurable preferences.
 * Corresponds to the `UserPreferences` schema.
 */
export interface UserPreferences {
  theme: 'dark' | 'light';
  notifications_enabled: boolean;
  editor_settings: Record<string, string>;
}

// --- Request Schemas ---

/**
 * Represents the payload for a user registration request.
 * Corresponds to `POST /api/auth/register`.
 */
export interface AuthRegisterRequest {
  username: string;
  email: string;
  password: string;
}

/**
 * Represents the payload for a user login request.
 * Corresponds to `POST /api/auth/login`.
 */
export interface AuthLoginRequest {
  username: string;
  password: string;
}

/**
 * Represents the payload for updating a user's profile.
 * Corresponds to `PATCH /api/users/me`.
 */
export interface UpdateUserRequest {
  username?: string;
  email?: string;
}

/**
 * Represents the payload for creating a new project.
 * Corresponds to `POST /api/projects`.
 */
export interface CreateProjectRequest {
  name: string; // 1-100 chars
  description?: string; // Max 500 chars
  settings?: {
    environment?: 'development' | 'staging' | 'production';
    version?: string; // Regex ^\d+\.\d+\.\d+$
  };
}

/**
 * Represents the payload for updating an existing project.
 * Corresponds to `PATCH /api/projects/{project_id}`.
 */
export interface UpdateProjectRequest {
  name?: string;
  description?: string;
  settings?: {
    environment?: 'development' | 'staging' | 'production';
    version?: string;
  };
}

// --- Response Schemas ---

/**
 * Represents the full user profile object returned by the API.
 * Corresponds to the `UserResponse` schema.
 */
export interface UserResponse {
  id: string; // UUID
  username: string;
  email: string;
  preferences: UserPreferences;
  created_at: string; // ISO-8601
  updated_at: string; // ISO-8601
}

/**
 * Represents a project's metadata and settings.
 * Corresponds to the `ProjectResponse` schema.
 */
export interface ProjectResponse {
  id: string; // UUID
  slug: string;
  owner_id: string; // UUID
  name: string;
  description: string | null;
  status: 'active' | 'archived' | 'maintenance';
  settings: {
    environment: 'development' | 'staging' | 'production';
    version: string;
  };
  created_at: string; // ISO-8601
  updated_at: string; // ISO-8601
}

/**
 * Represents a single asset within a project.
 * Corresponds to the `AssetResponse` schema.
 */
export interface AssetResponse {
  id: string; // UUID
  filename: string;
  virtualPath: string;
  assetType: 'code' | 'image' | 'audio' | 'text' | 'raw' | 'scene';
  mimeType: string;
  sizeBytes: number;
  sha256: string;
  previewUrl?: string;
  createdAt: string; // ISO-8601
  updatedAt: string; // ISO-8601
}

/**
 * Represents the aggregated index of assets for a project.
 * Corresponds to the `ProjectAssetIndexResponse` schema.
 */
export interface ProjectAssetIndexResponse {
  project_id: string; // UUID
  total_assets: number;
  total_size_bytes: number;
  assets: AssetResponse[];
}

/**
 * Represents the response from a successful login request.
 */
export interface LoginResponse {
  token: string;
  accessToken: string;
  tokenType: 'bearer';
}
